SELECT CONVERT(Date, CONVERT(DATE, DATEADD(HOUR, -4, DWSTOREDATETIME))) as ImportDate, DATEPART(HOUR, DATEADD(HOUR, -4, DWSTOREDATETIME)) as ImportHour
, COUNT(*) FilesImported
, COUNT(*) / 3600.0 as FilesPerSecond
from 
DW__Documents   /* Replace DW__Documents with your file cabinet that has imports coming in. */
where		DWSTOREDATETIME >= '2026-05-24 04:00'
group by CONVERT(Date, CONVERT(DATE, DATEADD(HOUR, -4, DWSTOREDATETIME))), DATEPART(HOUR, DATEADD(HOUR, -4, DWSTOREDATETIME))
ORDER BY CONVERT(Date, CONVERT(DATE, DATEADD(HOUR, -4, DWSTOREDATETIME))), DATEPART(HOUR, DATEADD(HOUR, -4, DWSTOREDATETIME))
